version: "3.8"

services:
  transaction-service:
    build:
      context: ./transaction-service         
      dockerfile: Dockerfile                 
    env_file: [./transaction-service/.env]
    ports: ["3000:3000"]                   
    depends_on:
      - kafka
      - qdrant-event

  antifraud-service:
    build:
      context: ./antifraud-service
      dockerfile: Dockerfile
    env_file: [./antifraud-service/.env]
    ports: ["3001:3001"]
    depends_on:
      - kafka
      - qdrant-event

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
    ports: ["9092:9092","9644:9644"]


  qdrant-event:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]

